# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a956ecb49a1ad3e8f1898a46ea3cc73e9381217be32025d3062d74a0f44e3e3911fafd5ad6393fec790bf7f20ac44adaf91d81bf7e940bdcc09e3a24df05e4d5

test:
  secret_key_base: 4915e476dbd94c58c390df8f1c0e9e9abe7ae4cc1b9de18edd6c63deb9bf617eaa7bf1f5a1d7be6c415b1252d5b639f0f23f4191520d783e4d09e2f6494ef064

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
